Basics


In [8]:
import numpy as np


In [9]:
arr_1D= np.array([1,2,3,4,5])
print("1D Array:", arr_1D)

1D Array: [1 2 3 4 5]


In [12]:
print("Multiplication by 2:", arr_1D * 2)

Multiplication by 2: [ 2  4  6  8 10]


In [42]:
print("zero matrix:", np.zeros((3, 4)))

print("one matrix:", np.ones((2, 5)))

print("Constant matrix:", np.full((3, 3), 7))

print("Random matrix:", np.random.rand(2, 3))

print("sequence array:", np.arange(0, 10))




zero matrix: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one matrix: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Constant matrix: [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random matrix: [[0.35118701 0.2856787  0.7177058 ]
 [0.51331294 0.60748421 0.40603158]]
sequence array: [0 1 2 3 4 5 6 7 8 9]


#Properties Of Arrays

In [43]:
arr= np.array([[1,2,3],[4,5,6]])
print("Array Properties:")
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Size:", arr.size)
print("Number of Dimensions:", arr.ndim)
print("Transpose:\n", arr.T)



Array Properties:
Shape: (2, 3)
Data Type: int64
Size: 6
Number of Dimensions: 2
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
