Operations

In [2]:
import numpy as np

Scalar Math

In [ ]:
arr=np.random.randint(low=1,high=20,size=10)
print("array:",arr)

# Scalar Math
print("Addition:",arr+5)
print("Subtraction:",arr-5)
print("Multiplication:",arr*5)
print("Division:",arr/5)
print("Exponentiation:",arr**2)
print("Modulus:",arr%5)




array: [16  9 11  4 12 18  2  6  4 11]
Addition: [21 14 16  9 17 23  7 11  9 16]
Subtraction: [11  4  6 -1  7 13 -3  1 -1  6]
Multiplication: [80 45 55 20 60 90 10 30 20 55]
Division: [3.2 1.8 2.2 0.8 2.4 3.6 0.4 1.2 0.8 2.2]
Exponentiation: [256  81 121  16 144 324   4  36  16 121]
Modulus: [1 4 1 4 2 3 2 1 4 1]
Array after adding 3: [19 12 14  7 15 21  5  9  7 14]


In [16]:
#scalar math on 2D array
arr2d=np.random.randint(low=1,high=20,size=(3,3))
print("2D array:\n",arr2d)
print("Addition:\n",arr2d+5)
print("Subtraction:\n",arr2d-5)
print("Multiplication:\n",arr2d*5)
print("Division:\n",arr2d/5)
print("Exponentiation:\n",arr2d**2)
print("Modulus:\n",arr2d%5)


2D array:
 [[14 18 18]
 [ 3  6 17]
 [11  9 15]]
Addition:
 [[19 23 23]
 [ 8 11 22]
 [16 14 20]]
Subtraction:
 [[ 9 13 13]
 [-2  1 12]
 [ 6  4 10]]
Multiplication:
 [[70 90 90]
 [15 30 85]
 [55 45 75]]
Division:
 [[2.8 3.6 3.6]
 [0.6 1.2 3.4]
 [2.2 1.8 3. ]]
Exponentiation:
 [[196 324 324]
 [  9  36 289]
 [121  81 225]]
Modulus:
 [[4 3 3]
 [3 1 2]
 [1 4 0]]


Arithmetic Operations

In [17]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("Array 1:",arr1)
print("Array 2:",arr2)

# Arithmetic Operations
print("Addition:",arr1+arr2)
print("Subtraction:",arr1-arr2)
print("Multiplication:",arr1*arr2)
print("Division:",arr1/arr2)


Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [18]:
#On 2D arrays
arr1_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2_2d=np.array([[9,8,7],[6,5,4],[3,2,1]])
print("2D Array 1:\n",arr1_2d)
print("2D Array 2:\n",arr2_2d)  
print("Addition:\n",arr1_2d+arr2_2d)
print("Subtraction:\n",arr1_2d-arr2_2d)
print("Multiplication:\n",arr1_2d*arr2_2d)
print("Division:\n",arr1_2d/arr2_2d)


2D Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2D Array 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Division:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


Aggregate Function

In [21]:
arr = np.array([1, 2, 3, 4])
print("Array:", arr)

# Aggregate Function
print("Sum:", np.sum(arr))
print("Product:", np.prod(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Average:",np.average(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))



Array: [1 2 3 4]
Sum: 10
Product: 24
Minimum: 1
Maximum: 4
Average: 2.5
Mean: 2.5
Median: 2.5


In [24]:
#on 2D array
arr_2d = np.random.randint(1, 10, size=(3, 3))
print("2D Array:\n", arr_2d)

print("Sum:\n", np.sum(arr_2d, axis=0))  # Sum of each column
print("Sum:\n", np.sum(arr_2d, axis=1))  # Sum of each row
print("Product:\n", np.prod(arr_2d, axis=0)) 
print("Product:\n", np.prod(arr_2d, axis=1))  
print("Minimum:\n", np.min(arr_2d, axis=0))
print("Minimum:\n", np.min(arr_2d, axis=1))
print("Maximum:\n", np.max(arr_2d, axis=0))
print("Maximum:\n", np.max(arr_2d, axis=1))


2D Array:
 [[2 5 5]
 [2 9 7]
 [2 2 4]]
Sum:
 [ 6 16 16]
Sum:
 [12 18  8]
Product:
 [  8  90 140]
Product:
 [ 50 126  16]
Minimum:
 [2 2 4]
Minimum:
 [2 2 2]
Maximum:
 [2 9 7]
Maximum:
 [5 9 4]


Searching

In [34]:
arr=np.array([10, 15, 20, 25, 30,20])
print("Array:",arr)

#Searching
print("indices equal to 20:",np.where(arr==20))
print("indices greater than 18:",np.where(arr>18))
print("indices less than 25:",np.where(arr<25))

indices = np.where(arr%2 == 0, "Even", "Odd")
print(indices)



Array: [10 15 20 25 30 20]
indices equal to 20: (array([2, 5]),)
indices greater than 18: (array([2, 3, 4, 5]),)
indices less than 25: (array([0, 1, 2, 5]),)
['Even' 'Odd' 'Even' 'Odd' 'Even' 'Even']


Comparing 

In [35]:
arr1 = np.random.randint(1,10, size=5)
arr2 = np.random.randint(1,10, size=5)
print("arr1: ", arr1)
print("arr2: ", arr2)

print("Equal:", arr1 == arr2)
print("Not Equal:", arr1 != arr2)
print("Greater Than:", arr1 > arr2)
print("Less Than:", arr1 < arr2)
print("Greater Than or Equal:", arr1 >= arr2)
print("Less Than or Equal:", arr1 <= arr2)

arr1:  [9 9 5 6 4]
arr2:  [2 2 6 1 4]
Equal: [False False False False  True]
Not Equal: [ True  True  True  True False]
Greater Than: [ True  True False  True False]
Less Than: [False False  True False False]
Greater Than or Equal: [ True  True False  True  True]
Less Than or Equal: [False False  True False  True]
