In [ ]:
import numpy as np


In [ ]:
mylist = [[1], [4], [2], [5], [3]]
arr = np.array(mylist)

Slicing


In [ ]:
arr=np.arange(12)
print("Slicing Example:", arr[2:8]) 
print("Slicing with Step:", arr[1:10:2])
print("Reversed Array:", arr[::-1])

print("\n2D array slicing example:")
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("Element at (1,2):", mat[1, 2])
print("Second Row:", mat[1, :])
print("Third Column:", mat[:, 2])
print("Submatrix (rows 0-1, cols 1-2):\n", mat[0:2, 1:3])




Slicing Example: [2 3 4 5 6 7]
Slicing with Step: [1 3 5 7 9]
Reversed Array: [11 10  9  8  7  6  5  4  3  2  1  0]

2D array slicing example:
Element at (1,2): 6
Second Row: [4 5 6]
Third Column: [3 6 9]
Submatrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]


Reshaping

In [ ]:
arr=np.arange(12)
print("Original Array:", arr)
reshaped_arr= arr.reshape((3,4))
print("Reshaped Array (3x4):\n", reshaped_arr)

arr_flat= reshaped_arr.flatten()
print("Flattened Array:", arr_flat)

Sorting

In [ ]:
arr = np.array([50, 20, 10, 40, 60])
sorted_arr = np.sort(arr)
print("Sorted Array:", sorted_arr)

arr_2d = np.array([[3, 1, 2],
                  [6, 5, 4],
                  [8, 7, 9]])

sorted_arr_2d = np.sort(arr_2d, axis=1)
print("Row-wise Sorted 2D Array:\n", sorted_arr_2d)
sorted_arr_2d_col = np.sort(arr_2d, axis=0)
print("Column-wise Sorted 2D Array:\n", sorted_arr_2d_col)



Sorted Array: [10 20 40 50 60]
Row-wise Sorted 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Column-wise Sorted 2D Array:
 [[3 1 2]
 [6 5 4]
 [8 7 9]]
